name: Deploy Nginx to Kubernetes

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR }}

      - name: Set version
        id: vars
        run: echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/nginx:${{ env.VERSION }} .

      - name: Push Docker image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/nginx:${{ env.VERSION }}
      
      - name: Update Kubernetes manifest with new image version
        run: |
          sed -i "s|image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/nginx:.*|image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/nginx:${{ env.VERSION }}|g" k8s/nginx-deployment.yaml
          git config --global user.email "your-email@example.com"  # Replace with your email
          git config --global user.name "Your Name"                # Replace with your name
          git add k8s/nginx-deployment.yaml
          git commit -m "Update Nginx image version to ${{ env.VERSION }}"
          git push https://${{ secrets.GH_TOKEN }}@github.com/2000ankita/nginx-cicd.git HEAD:main


