name: Deploy Nginx to Kubernetes

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Google Container Registry
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}

    - name: Build Docker image
      run: docker build -t gcr.io/YOUR_PROJECT_ID/nginx:latest .

    - name: Push Docker image
      run: docker push gcr.io/YOUR_PROJECT_ID/nginx:latest
